= Introduction

include::helgobox::partial$intro-header.adoc[]

|===
|Last update of text: |`2025-03-11 (v2.18.0-pre.3)`
|Last update of screenshots: |`2025-03-11 (v2.18.0-pre.3)`
|===

== What is Playtime?

link:https://www.helgoboss.org/projects/playtime[Playtime] is a powerful and versatile *session view* or *clip launcher* made specifically for the DAW link:https://www.reaper.fm[REAPER]. It is designed as a creative instrument for recording and triggering both audio and MIDI clips, making it ideal for *live performances*, *improvisation*, *jamming*, *looping* and *sketching arrangements*.

As part of the link:https://www.helgoboss.org/projects/helgobox[Helgobox] plug-in,
Playtime integrates seamlessly with REAPER by leveraging its unique native-speed extension API. This deep integration provides a smoother and more efficient user experience compared to using REAPER alongside other DAWs.

For a more detailed introduction to Playtime and a shiny presentation of its features, visit the link:https://www.helgoboss.org/projects/playtime[Playtime website].

== About this document

This reference provides a detailed guide to Playtime's usage, concepts, and features.

[TIP]
====

**You also might want to check out the link:https://github.com/helgoboss/helgobox/wiki/Playtime-Home[Playtime Wiki]!**

It is the place for user-contributed content and contains links to other related content, such as tutorials and guides.
====