...@includes/declarations.d2

direction: down

...@includes/absolute-control-start.d2
  
fire_mode_result -> control_absolute_incremental_buttons.is_zero_or_out_of_range: pass

control_absolute_incremental_buttons: @includes/control-absolute-incremental-buttons.d2
