...@includes/declarations.d2

direction: down

...@includes/absolute-control-start.d2

fire_mode_result -> pre_process_absolute_value.is_in_source_interval: pass


pre_process_absolute_value: @includes/pre-process-absolute-value.d2
pre_process_absolute_value.source_min_max -> prepare_absolute_value_no_performance_mode.control_transformation

prepare_absolute_value_no_performance_mode: @includes/prepare-absolute-value-no-performance-mode.d2
prepare_absolute_value_no_performance_mode.round_target_value-> hit_target_considering_max_jump.does_target_provide_value
prepare_absolute_value_no_performance_mode.value_sequence -> hit_target_considering_max_jump.does_target_provide_value

hit_target_considering_max_jump: @includes/hit-target-considering-max-jump.d2
hit_target_considering_max_jump.does_target_provide_value -> target: No (e.g. virtual target)
hit_target_considering_max_jump.which_takeover_mode -> hit_if_changed.is_target_retriggerable: Normal
hit_target_considering_max_jump.takover_mode_result -> hit_if_changed.is_target_retriggerable: pass


# Common end
...@includes/hit-if-changed-end.d2