= ReaLearn
:toc: preamble
:sectnumlevels: 2

image:https://github.com/helgoboss/realearn/actions/workflows/windows-x86_64.yml/badge.svg[Windows x86_64,link=https://github.com/helgoboss/realearn/actions/workflows/windows-x86_64.yml]
image:https://github.com/helgoboss/realearn/actions/workflows/windows-i686.yml/badge.svg[Windows i686,link=https://github.com/helgoboss/realearn/actions/workflows/windows-i686.yml]
image:https://github.com/helgoboss/realearn/actions/workflows/macos-x86_64.yml/badge.svg[macOS x86_64,link=https://github.com/helgoboss/realearn/actions/workflows/macos-x86_64.yml]
image:https://github.com/helgoboss/realearn/actions/workflows/macos-aarch64.yml/badge.svg[macOS aarch64,link=https://github.com/helgoboss/realearn/actions/workflows/macos-aarch64.yml]
image:https://github.com/helgoboss/realearn/actions/workflows/linux-x86_64.yml/badge.svg[Linux x86_64,link=https://github.com/helgoboss/realearn/actions/workflows/linux-x86_64.yml]
image:https://github.com/helgoboss/realearn/actions/workflows/linux-aarch64.yml/badge.svg[Linux aarch64,link=https://github.com/helgoboss/realearn/actions/workflows/linux-aarch64.yml]
image:https://github.com/helgoboss/realearn/actions/workflows/linux-armv7.yml/badge.svg[Linux armv7,link=https://github.com/helgoboss/realearn/actions/workflows/linux-armv7.yml]
image:https://img.shields.io/badge/license-GPL-blue.svg[GitHub license,link=https://raw.githubusercontent.com/helgoboss/realearn/master/LICENSE]
image:https://img.shields.io/badge/Donate-PayPal-orange.svg[Donate,link=https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=9CTAK2KKA8Z2S&source=url]

Sophisticated https://www.reaper.fm/[REAPER] MIDI/OSC-learn VST instrument plug-in for controlling REAPER with feedback.

== Installation

The easiest and preferred way of installing ReaLearn is via https://reapack.com/[ReaPack], a
sort of "app store" for REAPER. It allows you to keep your installation of ReaLearn up-to-date very easily.

=== Install for the first time

If you previously installed ReaLearn manually, please uninstall it first!

. Install https://reapack.com/[ReaPack] if not done so already
. Extensions → ReaPack → Import repositories…
. Copy and paste the following repository URL:
+
 https://github.com/helgoboss/reaper-packages/raw/master/index.xml
+
. Extensions → ReaPack → Browse packages…
. Search for `realearn`
. Right mouse click on the ReaLearn package → Install…
. OK or Apply
. Restart REAPER

=== Update to the latest stable version

ReaLearn development moves fast. In order to take advantage of new features, improvements and fixes, you should check for updates from time to time.

. Extensions → ReaPack → Synchronize packages
** It will tell you if a new version has been installed.
. Restart REAPER

=== Test new features and improvements

If you want to get access to cutting-edge but untested versions of ReaLearn, you have two options:

Install a specific pre-release:

. Right mouse click on the ReaLearn package → Versions
. Select any version ending on `-pre.*` or `-rc.*`
. OK or Apply
. Restart REAPER

Enable pre-releases globally:

. Extensions → ReaPack → Manage repositories → Options… → Enable pre-releases globally (bleeding edge)
. After that, whenever you synchronize packages, you will get the latest stuff.

=== Install manually

If you are more the download type of person, you can find the latest `dll`, `dylib` and `so` files here at
GitHub on the https://github.com/helgoboss/realearn/releases[releases page] for manual installation.
You also must install ReaLearn manually if you plan to use ReaLearn in both REAPER for Windows 32-bit
and REAPER for Windows 64-bit because then it's important to use two separate VST plug-in directories.

*Please note that it's impossible to run ReaLearn as a bridged plug-in.* If you have
"Preferences → Plug-ins → Compatibility → VST bridging/firewalling" set to "In separate plug-in process" or
"In dedicated process per plug-in", you will need to add an exception for ReaLearn by setting "Run as" to
"Native only"!

== Usage

=== User guide
The user guide of the latest not-yet-released version is available as
https://github.com/helgoboss/realearn/blob/master/doc/user-guide.adoc[HTML (GitHub)] (preferred, best readability).

A complete user guide for the latest release is available as
https://github.com/helgoboss/realearn/releases/latest/download/realearn-user-guide.pdf[PDF] and
https://www.helgoboss.org/projects/realearn/user-guide[HTML (website)].

=== Video

We also have an https://www.youtube.com/watch?v=dUPyqYaIkYA[introduction video]. Watch 2 minutes to get a first
impression and stay tuned if you are interested in the details.

=== Quick start

ReaLearn is fired up just like any other VST instrument in REAPER: By adding it to an FX chain.

*Main panel (containing the list of mappings):*

*Mapping panel (for editing one particular mapping):*

== Architecture

See link:ARCHITECTURE.adoc[here].

== Contributing

See link:CONTRIBUTING.adoc[here].

== Links

* https://www.helgoboss.org/projects/realearn/[Website]
* http://forum.cockos.com/showthread.php?t=178015[Forum] (dedicated thread in REAPER forum)
* https://github.com/helgoboss/realearn/issues[Issue tracker]
* https://bitbucket.org/helgoboss/realearn/issues[Old issue tracker] (for ReaLearn &lt; v1.10.0)
* https://github.com/helgoboss/realearn-companion[ReaLearn Companion app]
