
= Key concepts

This section provides short descriptions of ReaLearn's key concepts.
A good understanding of those concepts is key to use ReaLearn effectively, no matter which of its many features you are going to use.

[[control]]
== Control

In ReaLearn, the word _control_ most of the time refers to the process of triggering or adjusting something in REAPER (e.g. triggering an action or adjusting a FX parameter).

[[feedback]]
== Feedback

In ReaLearn, the word _feedback_ refers to the process of controlling LEDs, motor faders or displays on your device, in response to events in REAPER (e.g. a track volume change).

[[controller]]
== Controller

A controller is the device that you want to use for controlling REAPER.
Most of the time, it's a hardware device, for example a MIDI keyboard or control surface.
But it could just as well be a software, for example an OSC app.

[[control-element]]
== Control element

A control element is anything that you can use to control something.
In most cases, it's a piece of plastic on your hardware controller.

Examples: Knobs, encoders, faders, buttons, keys, pads, pitch wheels, acceleration sensors.

[[control-element-interaction]]
== Control element interaction

A control element interaction is the action of using a <<control-element>>.

Most often, there's exactly one type of interaction you can do with a certain control element:

* _Turning_ a knob
* _Pressing/releasing_ a button
* _Moving_ a fader

But sometimes, one <<control-element>> can be used in multiple ways:

* _Moving_ a touch-sensitive fader
* _Touching/releasing_ a touch-sensitive fader

In this reference, when we write <<control-element>>, we often actually mean <<control-element-interaction>>.
Because most of the time, they are essentially the same.

[[feedback-element]]
== Feedback element

A feedback element is anything on your controller that can indicate or display something.

Examples: LEDs, motor faders, displays.

Very frequently, control elements and feedback elements are combined:

- Button with an integrated LED
- Encoder with am LED ring
- Motor fader

That's why this reference sometimes uses the term <<control-element>> even if it's referring to the corresponding <<feedback-element>>, too.

[[input-port]]
== Input port

For letting you control things, ReaLearn somehow needs to react to events coming from your <<controller>>.
It does so by listening to events from an input port, which can be a MIDI input device port, an OSC port or your computer keyboard.

You can change the input port using the xref:user-interface/main-panel/inputoutput-section.adoc#input-menu[].

[[output-port]]
== Output port

For sending <<feedback>> back to your controller, ReaLearn needs to somehow send instructions back to your <<controller>>.
It does so by connecting to an output port, which can be a MIDI output device port or an OSC port.

You can change the output port using the xref:user-interface/main-panel/inputoutput-section.adoc#output-menu[].

[[instance]]
== Instance

Helgobox/ReaLearn is an instrument plug-in.
That means you can add multiple instances of it, just as you would add multiple instances of a synth or effect.
For example, one instance could be on the monitoring FX chain and two instances somewhere in your project.

[[unit]]
== Unit

Each ReaLearn <<instance>> contains at least one unit, the so-called _main unit_.
But it may contain an arbitrary number of additional units.

Units are like "mini instances" within one real ReaLearn <<instance>>.
They make it possible that one ReaLearn <<instance>> can deal with many controllers at the same time.
Each unit has its own <<input-port>>, <<output-port>>, <<controller-compartment>>, <<main-compartment>>, xref:further-concepts/compartment-concepts.adoc#controller-preset[], xref:further-concepts/compartment-concepts.adoc#main-preset[], and so on.

[[compartment]]
== Compartment

Each unit consists of exactly two compartments.
A compartment is a self-contained list of mappings that can be saved as independent preset.
The two compartments available in each unit are:

[[main-compartment]] Main compartment::
This compartment is the most important compartment.
Its purpose is to define what the controller device should do, e.g. letting a fader control the volume of a track or projecting the name of an FX parameter to a hardware display.
+
We call the mappings in this compartment [[main-mapping,Main mapping]] _main mappings_ and the presets _main presets_.

[[controller-compartment]] Controller compartment::
Usage of the controller compartment is optional.
It has two main purposes: Describing all control elements which a controller has, giving them descriptive names and enabling xref:further-concepts/compartment-concepts.adoc#virtual-control[].
+
We call the mappings in this compartment [[controller-mapping,Controller mapping]] _controller mappings_ and the presets _controller presets_.

[#mapping]
== Mapping

Each compartment consists of a list of mappings.
A mapping is arguably the most important concept in Realearn.
It connects a <<control-element>> and/or <<feedback-element>> on your <<controller>> with an action or parameter in REAPER.

=== Anatomy of a mapping

Each mapping in ReaLearn is composed of 3 elements:

<<source>>:: Describes the <<control-element>> and/or <<feedback-element>> on the <<controller>>.

<<target>>:: Something in REAPER that wants to be controlled and/or provides feedback, e.g. track volume or cursor position or an action.

<<glue>>:: A processor that sits between <<source>> and <<target>> and filters or transforms <<control>> and <<feedback>> streams.

[[source]]
== Source

A _source_ is part of a <<mapping>> and describes in most cases a <<control-element>> and/or <<feedback-element>> on a <<controller>>.
In a more general sense it can be anything that emits xref:further-concepts/mapping-concepts.adoc#control-value[control values].

We distinguish between <<virtual-source, virtual sources>> and <<real-source, real sources>>.

[[virtual-source]]
=== Virtual source

A _virtual_ source refers to a xref:further-concepts/compartment-concepts.adoc#virtual-control-element[] and can only be used in the <<main-compartment>>.

Examples: `ch1/fader`

[[real-source]]
=== Real source

A _real_ source refers to a xref:further-concepts/compartment-concepts.adoc#real-control-element[].

Examples: MIDI source, OSC source

[[glue]]
== Glue

A _glue_ is part of a <<mapping>> and sits between the source and the target and filters or transforms control and feedback streams.

[[target]]
== Target

A _target_ is part of a <<mapping>> and represents something (mostly something in REAPER) that wants to be controlled and/or provides feedback.

We distinguish between <<virtual-target, virtual targets>> and <<real-target, real targets>>.

[[virtual-target]]
=== Virtual target

A _virtual_ target controls a xref:further-concepts/compartment-concepts.adoc#virtual-control-element[] and can only be used in the <<controller-compartment>>.

Example: `ch1/fader`

It's then picked up by a <<virtual-source>> in the <<main-compartment>>.

[[real-target]]
=== Real target

All others targets are real.

Examples: xref:target-types/track-targets/track-set-volume.adoc#track-set-volume[]

[[learning]]
== Learning

This section can't be complete without mentioning the concept that inspired ReaLearn's name: _Learning_.
Learning simply means that you press a _Learn_ button instead of doing manual setup.
This can save a lot of time!

In ReaLearn, you can learn <<source, sources>> and <<target, targets>>.

[[learn-source]]
=== Learn source

Sources can be learned by pressing a source learn button and then touching a <<control-element>> on your controller.
This saves you from the tedious job of setting up MIDI or OSC sources manually.

[[learn-target]]
=== Learn target

Targets can be learned by pressing a target learn button and then invoking a <<target>> within REAPER.
This saves you from choosing xref:further-concepts/target-concepts.adoc#target-object-selectors[] and other stuff manually.
