= Key concepts

This section offers brief descriptions of ReaLearn's key concepts.
A solid understanding of these concepts is essential for effectively using ReaLearn, regardless of which features you plan to utilize.

[[control]]
== Control

In ReaLearn, the term _control_ typically refers to the process of triggering or adjusting something in REAPER, such as executing an action or modifying an FX parameter.

[[feedback]]
== Feedback

In ReaLearn, the term _feedback_ refers to controlling LEDs, motorized faders, or displays on your device in response to events in REAPER, such as a track volume change.

[[controller]]
== Controller

A _controller_ is the device you use to control REAPER.
It is usually a hardware device, such as a MIDI keyboard or control surface, but it can also be software, like an OSC app.

[[control-element]]
== Control element

A control element is any component you can use to control something.
In most cases, it's a physical part of your hardware <<controller>>.

Examples include knobs, encoders, faders, buttons, keys, pads, pitch wheels and acceleration sensors.

[[control-element-interaction]]
== Control element interaction

A control element _interaction_ is the act of using a <<control-element>>.

Typically, each control element has one primary interaction type:

* _Turning_ a knob
* _Pressing/releasing_ a button
* _Moving_ a fader

However, some control elements allow multiple interactions:

* _Moving_ a touch-sensitive fader
* _Touching/releasing_ a touch-sensitive fader

In this reference, <<control-element>> often implies <<control-element-interaction>>, as they are usually synonymous.

[[feedback-element]]
== Feedback element

A _feedback element_ is any part of your <<controller>> that can indicate or display information.

Examples includes LEDs, motor faders and displays.

Very frequently, control elements and feedback elements are combined:

- Button with an integrated LED
- Encoder with an LED ring
- Motorized fader

For this reason, this reference sometimes uses <<control-element>> to refer to both the <<control-element>> and the corresponding <<feedback-element>>.

[[input-port]]
== Input port

To enable control, ReaLearn needs to respond to events from your <<controller>>.
It achieves this by listening to events from an _input port_, which can be a MIDI device port, an OSC port or your computer keyboard.

You can change the input port using the xref:user-interface/main-panel/inputoutput-section.adoc#input-menu[].

[[output-port]]
== Output port

To send <<feedback>> back to your <<controller>>, ReaLearn transmits instructions through an _output port_, which can be a MIDI device port or an OSC port.

You can change the output port using the xref:user-interface/main-panel/inputoutput-section.adoc#output-menu[].

[[instance]]
== Instance

Helgobox/ReaLearn is an instrument plug-in.
That means you can add multiple instances of it, just as you would add multiple instances of a synth or effect.
For example, you could place one instance on the monitoring FX chain and two instances somewhere in your project.

[[unit]]
== Unit

Each ReaLearn <<instance>> contains at least one _unit_, known as the _main unit_, but it can also contain an arbitrary number of additional units.

Units function like "mini instances" within a single ReaLearn <<instance>>, allowing that instance to manage multiple controllers simultaneously.
Each unit has its own <<input-port>>, <<output-port>>, <<controller-compartment>>, <<main-compartment>>, xref:further-concepts/compartment-concepts.adoc#controller-preset[], xref:further-concepts/compartment-concepts.adoc#main-preset[], and more.

[[compartment]]
== Compartment

Each unit consists of two compartments.
A compartment is a self-contained list of mappings that can be saved as an independent preset.
The two compartments in each unit are:

[[main-compartment]] Main compartment::
This is the primary compartment.
Its purpose is to define what the controller device should do, e.g., allowing a fader to control track volume or displaying the name of an FX parameter on a hardware display.
+
We refer to the mappings in this compartment as [[main-mapping,Main mapping]] _main mappings_ and to the presets as _main presets_.

[[controller-compartment]] Controller compartment::
The controller compartment is optional and serves two main purposes: Describing all control elements of the controller, assigning them descriptive names and enabling xref:further-concepts/compartment-concepts.adoc#virtual-control[].
+
We refer to the mappings in this compartment as [[controller-mapping,Controller mapping]] _controller mappings_ and to the presets as _controller presets_.

[#mapping]
== Mapping

Each compartment contains a list of mappings.

A _mapping_ connects a <<control-element>> and/or <<feedback-element>> on your <<controller>> with an action or parameter in REAPER.

=== Anatomy of a mapping

Each mapping in ReaLearn consists of three elements:

<<source>>:: Describes the <<control-element>> and/or <<feedback-element>> on the <<controller>>.

<<target>>:: Something in REAPER that is to be controlled or provides feedback, such as track volume, cursor position or an action.

<<glue>>:: A processor that sits between <<source>> and <<target>>, filtering and transforming <<control>> and <<feedback>> streams.

[[source]]
== Source

A _source_ is part of a <<mapping>> and describes in most cases a <<control-element>> and/or <<feedback-element>> on a <<controller>>.
In a more general sense it can be anything that emits xref:further-concepts/mapping-concepts.adoc#control-value[control values].

We distinguish between <<virtual-source, virtual sources>> and <<real-source, real sources>>.

[[virtual-source]]
=== Virtual source

A _virtual_ source refers to a xref:further-concepts/compartment-concepts.adoc#virtual-control-element[] and can only be used in the <<main-compartment>>.

Examples: `ch1/fader`

[[real-source]]
=== Real source

A _real_ source refers to a xref:further-concepts/compartment-concepts.adoc#real-control-element[].

Examples: MIDI source, OSC source

[[glue]]
== Glue

A _glue_ is part of a <<mapping>> and sits between the source and the target and filters or transforms control and feedback streams.

[[target]]
== Target

A _target_ is part of a <<mapping>> and represents something (mostly something in REAPER) that wants to be controlled and/or provides feedback.

We distinguish between <<virtual-target, virtual targets>> and <<real-target, real targets>>.

[[virtual-target]]
=== Virtual target

A _virtual_ target controls a xref:further-concepts/compartment-concepts.adoc#virtual-control-element[] and can only be used in the <<controller-compartment>>.

Example: `ch1/fader`

It's then picked up by a <<virtual-source>> in the <<main-compartment>>.

[[real-target]]
=== Real target

All others targets are real.

Examples: xref:target-types/track-targets/track-set-volume.adoc#track-set-volume[]

[[learning]]
== Learning

This section can't be complete without mentioning the concept that inspired ReaLearn's name: _Learning_.
Learning simply means that you press a _Learn_ button instead of doing manual setup.
This can save a lot of time!

In ReaLearn, you can learn <<source, sources>> and <<target, targets>>.

[[learn-source]]
=== Learn source

Sources can be learned by pressing a source learn button and then touching a <<control-element>> on your controller.
This saves you from the tedious job of setting up MIDI or OSC sources manually.

[[learn-target]]
=== Learn target

Targets can be learned by pressing a target learn button and then invoking a <<target>> within REAPER.
This saves you from choosing xref:further-concepts/target-concepts.adoc#target-object-selectors[] and other stuff manually.
