name: Check
description: Check Rust code via Clippy
inputs:
  args:
    description: 'Cargo arguments'
    required: false
    default: ''
runs:
  using: "composite"
  steps:
    - name: Install Rust
      uses: dtolnay/rust-toolchain@1.84.0
      with:
        components: clippy

    - name: Set up dependencies
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install nasm php libudev-dev libxdo-dev libx11-dev  libxcursor-dev libxcb-dri2-0-dev libxcb-icccm4-dev libx11-xcb-dev mesa-common-dev libgl1-mesa-dev libglu1-mesa-dev libspeechd-dev libgtk-3-dev
      shell: sh

    - name: Rust cache
      uses: swatinem/rust-cache@v2

    - name: cargo clippy
      env:
        ARGS: ${{ inputs.args }}
      run: cargo clippy $ARGS -- -D warnings
      shell: sh