blank_issues_enabled: false
contact_links:
  - name: GitHub Community Support
    url: https://github.com/helgoboss/helgobox/discussions/categories/q-a
    about: Please ask and answer questions here.
  - name: GitHub Idea Tracker
    url: https://github.com/helgoboss/helgobox/discussions/categories/ideas?discussions_q=category%3AIdeas+is%3Aopen+sort%3Adate_created+
    about: Request a new feature or suggest an improvement here.