= Use grid controllers

.Grid controllers are optional!
TIP: You don't need a xref:key-concepts.adoc#grid-controller[] to use Playtime! However, using one adds a tactile dimension to the clip-launching experience, making Playtime feel more like a distinct musical instrument. It’s a fun way to enhance interaction and creativity.

If your xref:key-concepts.adoc#grid-controller[] is on the link:https://github.com/helgoboss/helgobox/wiki/Playtime-Controllers[list of supported devices], here's how you set it up:

. Ensure that Playtime is running and you see its xref:user-interface.adoc[].
. If the device is already connected to the USB port, **disconnect it** and wait a few seconds!
. **Connect** the device to the USB port.
. After waiting for a few seconds, Playtime should show a green success notice at the bottom of the screen.

After that, the device should visually reflect the contents of the Playtime xref:key-concepts.adoc#matrix[] and you should be able to control the matrix with it.

In addition, the device should now appear in the xref:realearn:ROOT:user-interface/settings-dialog.adoc#controllers[ReaLearn controllers] section of the xref:helgobox::app/user-interface/settings-dialog.adoc[]. This is also the place where you can manually set up the device in case it was not auto-detected.


== Related videos

video::tkyNCGOVumw[youtube, list={youtube_playtime_tutorials_list_id}]