[package]
name = "helgobox-allocator"
version = "0.1.0"
authors = ["Benjamin Klum <benjamin.klum@helgoboss.org>"]
edition = "2021"
publish = false

[dependencies]
once_cell.workspace = true
backtrace = "0.3.69"