= Menu bar

include::partial$realearn-specific-ui-elements.adoc[]

== Menu button

This opens the main menu of Helgobox/ReaLearn.
The same menu opens when you right-click an empty area.

It provides the following general entries.

[[open-pot-browser]] Open Pot Browser::
This will open Pot Browser.
See xref:products.adoc#pot-browser[] for details.

[[show-app]] Show App::
Shows the xref:helgobox::app.adoc[] associated with this xref:helgobox::key-concepts.adoc#instance[].

[[close-app]] Close App::
Closes the xref:helgobox::app.adoc[] associated with this xref:helgobox::key-concepts.adoc#instance[].

[[server]] Server::
Helgobox features a built-in server which allows the old ReaLearn Companion App (and in the future also the xref:helgobox::app.adoc[]) to connect to Helgobox.
The server runs globally, not per instance!

Enable and start!::: This starts the server and makes sure it will automatically be started next time you use Helgobox.
Disable and stop!::: This stops the server and makes sure it will not be started next time you use Helgobox.
Add firewall rule::: Attempts to add a firewall rule for making the server accessible from other devices or displays instructions how to do it.

[[export-to-clipboard]]
== Export to clipboard button

Pressing the export button allows you to copy Helgobox settings to the clipboard so you can import them in another instance or edit them in a link:https://en.wikipedia.org/wiki/Text_editor[text editor].

--
The following list only describes the general-purpose menu entries. For the rest, see:

* xref:realearn::user-interface/main-panel/menu-bar.adoc#export-to-clipboard-button[ReaLearn entries]
* xref:playtime::user-interface/menus/export-to-clipboard-menu.adoc[Playtime entries]
--

Export instance as JSON::
Copies a _complete_ dump of this xref:key-concepts.adoc#instance[] to the clipboard in JSON format.

[[import-from-clipboard]]
== Import from clipboard button

Pressing the import button does the opposite: It restores whatever Helgobox dump is currently in the clipboard.
It supports JSON or Luau.

[[help]]
== Help button (?)

Provides links to the reference and other documentation.
