[#realearn-load-mapping-snapshot]
= ReaLearn: Load mapping snapshot

Restores target values for all or certain mappings in this ReaLearn unit.

== Snapshot menu

Choose the snapshot that you want to load.

<Initial>:: Restores the initial target values for the mappings.

By ID:: Restores target values contained in a snapshot that was taken via xref:target-types/realearn-targets/realearn-take-mapping-snapshot.adoc#realearn-take-mapping-snapshot[].
Enter the corresponding ID here.

== Default field

Allows you to define a default target value to restore for each participating mapping whenever the snapshot either doesn't exist or doesn't contain a value for that mapping.
If that participating mapping has reverse checked, the inverse of the default value will be loaded.

== Tags field

Allows you to restrict the set of mappings whose target values will be restored.

* If this field is empty, target values of all mappings will be restored.
* If this field contains tags (comma-separated), target values will be restored only for mappings that are tagged with any of these.

== Active mappings only checkbox

By default, even target values for inactive (but control-enabled) mappings are restored!
If you don't like that, tick this checkbox.

== Remarks

* Mappings for which control is not enabled, never participate in snapshotting.
* Some targets don't report values and therefore don't participate in snapshotting.
* Feedback of this target indicates whether the desired snapshot is the one which has last been loaded (for the given tags).