= Behringer MOTÖR 61/49

== Basics

TIP: The term "Banks" in mapping or file names refer to hardware/firmware switched banks, not virtual banks created within ReaLearn.

== Device configuration

All mappings are intended to work with the default Motör configuration in MIDI mode.

== Feedback

=== Faders and encoders

Feedback is fully functional for faders and encoders.
Although the Motör allows encoders to be configured as relative controls, feedback seems to break in relative mode. Absolute mode (the default) works reliably.

=== Pads

Each pad has an illuminated back-light that turns on while the pad is pressed, and the colour of the light is menu-configurable. Unfortunately it seems that there is no other way to control illumination, so the feature is cosmetic at best. Motör MIDI information in the user documentation is scanty, and non-existent regarding MIDI feedback. Web searches haven't helped. Pad mappings are provided without feedback.

=== Transport buttons

Transport buttons illuminate, but as with the pads no MIDI feedback control seems to be available. Motör's inbuilt default configuration is not ideal but better than no feedback at all.

== Presets


[cols="1,m,1"]
|===
| Preset | File name | Description

| Behringer Motör 61/49
| behringer-motoer.json
|
Controller mapping with faders, encoders, pads for all firmware banks.
Mod & pitch wheels plus expression & sustain pedals are added for convenience.
A companion projection is provided.

This mapping is too cluttered for practical use, and is intended as a convenient template for deriving other controller mappings.

| Behringer Motör 61/49 Bank 1 - 4
| behringer-motoer-bank*.json
|
Controller mappings with faders, encoders, pads for each of firmware banks 1 to 4.

Companion projections are provided.

| Behringer Motör Transport
| behringer-motoer-transport.json
|

Controller mapping with transport buttons & sustain pedal only.

No companion projection is provided.

| Motör Transport Switched
| motor-transport-switched.json
|
Sample main mapping with transport buttons & sustain pedal only, recommended for use in Reaper's Monitoring FX chain.

Controls are hard-coded, rather than derived from a controller mapping.
The sustain pedal switches previous/next functions between stepping by bar (measure) or stepping by marker, and showcases Realearn's handy "enable/disable mappings" feature.
|===