classes: {
  start: {
    style.fill: deepskyblue
  }
  end: {
    style.fill: lime
  }
  decision: {
    shape: diamond
    width: 100
  }
  discard: {
    label: discard
    style.fill: orange
  }
}

source: {
  label: Source
  class: start
}

target: {
  label: Target
  class: end
}

# (* -> *)[*] {
#   # style.animated: true
# }
