classes: {
  start: {
    style.fill: "#BDD0D8"
  }
  end: {
    style.fill: "#EEE0C9"
  }
  decision: {
    shape: diamond
    width: 100
  }
  discard: {
    shape: image
    label: ""
    icon: https://icons.terrastruct.com/essentials%2F037-stop.svg
    # icon: ./discard.svg
    width: 50
    height: 50
  }
  container: {
    label: ""
    style.fill: "#F1F0E8"
  }
  portal: {
    icon: https://icons.terrastruct.com/essentials%2F036-play%20button.svg
    width: 50
    height: 50
  }
}

source: {
  label: Source
  class: start
}

target: {
  label: Target
  class: end
}
