class: container

discard1.class: discard
discard2.class: discard

is_target_retriggerable -> does_target_have_desired_value: no
does_target_have_desired_value -> discard1: yes
is_target_retriggerable: {
  label: Is target retriggerable?
  class: decision
}
does_target_have_desired_value: {
  label: Does target already have the desired value?
  class: decision
}
