name: Post-checkout
description: Checkout with Playtime Engine
runs:
  using: "composite"
  steps:
    # Checkout with Playtime Engine
    - name: Setup ssh-agent
      uses: webfactory/ssh-agent@v0.9.1
      with:
        ssh-private-key: |
          ${{ secrets.PRIVATE_PLAYTIME_CLIP_ENGINE_DEPLOY_KEY }}
          ${{ secrets.PRIVATE_HELGOBOSS_LICENSE_PROCESSOR_DEPLOY_KEY }}

    - name: Update submodules
      run: |
        git submodule update --init
