name: Post-checkout
description: Checkout with Playtime Engine
inputs:
  playtime-engine-deploy-key:
    description: 'Playtime Engine deploy key'
    required: true
  license-processor-deploy-key:
    description: 'License Processor deploy key'
    required: true
runs:
  using: "composite"
  steps:
    # Checkout with Playtime Engine
    - name: Setup ssh-agent
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: |
          ${{ inputs.playtime-engine-deploy-key }}
          ${{ inputs.license-processor-deploy-key }}

    - name: Update submodules
      run: |
        git submodule update --init
      shell: sh
