
= Track: Peak

This is a feedback-only target!
It turns your feedback-capable controller into a VU meter by constantly reporting the current volume of the configured track to it.

In addition to connecting it with a LED ring or motor fader source (which should be obvious), it can also be used with a single LED to build a clipping indicator:

. Set _Target Min_ to the minimum dB value that should make your clipping LED turn on.
Leave _Target Max_ at 12.00 dB.
. Make sure the xref:user-interface/mapping-panel/glue-section.adoc#out-of-range-behavior[] is set to "Min or max".
. If you have an LED that supports multiple colors, you will probably see a rainbow of colors flashing up which can be quite confusing.
Use the feedback transformation formula `x = ceil(y)` to restrict the feedback to just two values:
Min (0%) or Max (100%).
You can then use xref:user-interface/mapping-panel/glue-section.adoc#source-min-max[] to adjust the off/on LED colors.

At the moment this target only reports peak volume, not RMS.