= ReaLearn - Main Presets
:toc:
:toclevels: 5
:sectnums:
:sectnumlevels: 2

== Introduction

The number of factory _main_ presets in the Helgoboss ReaPack repository and the https://github.com/helgoboss/realearn/tree/master/resources/main-presets/unofficial[list of unofficial main presets] is relatively small because ReaLearn is all about enabling you
to quickly come up with your own customized mappings. Except main presets for Playtime, the few main presets available primarily serve as inspiration and as starting point for your own presets.

== Preset stability

Whenever you like a certain factory preset and want it
to be stable, it's best if you make your own copy of it using *Save as...* and use this one instead (because I might update it at a later point, potentially introducing changes that you don't want).

== Main presets vs. controller presets

Another purpose of the main presets in this repository is to demonstrate one big advantage of separating controller
presets from main presets: You can freely combine them on a mix-and-match basis. This enables you to get out-of-the-box
access to all kinds of interesting control scenarios with potentially very different controllers.

=== Virtual control schemes

Speaking of _freely_. Of course, this only works as long as controller and main presets share the same philosophy
and virtual control element naming/numbering. **A main preset is not automagically compatible with any controller preset!**
As you can imagine, there are far too many types of controllers and control scenarios out there to make this
work in all cases. However, ReaLearn provides many means to get close to this ideal.

In order to make it easier for users to know which main presets are compatible with which controller presets, ReaLearn has the concept of so-called **virtual control schemes**. For now, the following schemes are considered:

* *DAW:* For typical Mackie-style DAW control elements.
* *Grid:* For grid control elements such as the ones on the Launchpad.
* *Numbered:* For control elements that are best represented as increasing numbers, e.g. a simple generic row of knobs.

The general idea is:

* A controller preset _provides_ an arbitrary number of schemes.
** E.g. the Akai APC Key 25 provides control elements of all the mentioned schemes.
** A controller should not double-expose one single control element under different virtual control element names.
* A main preset _uses_ an arbitrary number of schemes.
** E.g. they could assign a track volume change to both the numbered multi control element 5 (_Numbered_  scheme) and to the named multi control element `ch5/fader` (_DAW_ scheme) by using 2 mappings with the same target. Then we say this preset uses both schemes.

=== How main presets can leverage virtual control schemes

There are roughly 3 kinds of main presets:

. **Controller-specific main presets without virtual sources:** They are built for one specific controller and use MIDI/OSC sources directly.
. **Controller-specific main presets with virtual sources:** They are built for one specific controller but primarily use virtual sources (e.g. in order to take advantage of ReaLearn's projection feature).
. **Reusable main presets:** Thy are built for all controllers that provide a specific control scheme.

== Main presets

=== DAW control

*Used virtual control schemes:* DAW

* A preset that emulates the typical "Mackie Control"-style DAW control. Not completely, but a large part.
* Is compatible with any controller preset that provides the DAW scheme.
* Tested with controllers X-Touch One and iCON Platform M+ so far.
* Is a perpetual work in progress and will be improved over time.