on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:
  # For quickly detecting important differences in runner configurations
  schedule:
    - cron: '0 5 * * MON'

name: Linux armv7

jobs:
  check:
    name: Build
    runs-on: ubuntu-22.04
    steps:
      # Checkout with Playtime Clip Engine
      - uses: actions/checkout@v2
      - uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: |
            ${{ secrets.PRIVATE_PLAYTIME_CLIP_ENGINE_DEPLOY_KEY }}
            ${{ secrets.PRIVATE_HELGOBOSS_LICENSE_PROCESSOR_DEPLOY_KEY }}
      - name: Update submodules
        run: |
          git submodule update --init
      # Remainder
      - name: Set up dependencies
        run: |
          sudo apt-get update
          sudo apt-get install nasm php libudev-dev libxdo-dev libx11-dev  libxcursor-dev libxcb-dri2-0-dev libxcb-icccm4-dev libx11-xcb-dev mesa-common-dev libgl1-mesa-dev libglu1-mesa-dev libspeechd-dev libgtk-3-dev
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: 1.84.0
          target: armv7-unknown-linux-gnueabihf
          override: true
      - name: cargo test (for generating dialogs with php)
        uses: actions-rs/cargo@v1
        env:
          RUST_MIN_STACK: 5242880
        with:
          command: test
      - name: cargo build
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --target armv7-unknown-linux-gnueabihf