on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:
  # For quickly detecting important differences in runner configurations
  schedule:
    - cron: '0 5 * * MON'

name: Windows i686

jobs:
  test:
    name: Build
    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: ./.github/actions/post-checkout
        with:
          playtime-engine-deploy-key: ${{ secrets.PRIVATE_PLAYTIME_CLIP_ENGINE_DEPLOY_KEY }}
          license-processor-deploy-key: ${{ secrets.PRIVATE_HELGOBOSS_LICENSE_PROCESSOR_DEPLOY_KEY }}
      - uses: ./.github/actions/build
        with:
          # Prevent "LLVM ERROR: out of memory"
          args: '--features egui --profile dev-llvm-out-of-memory-fix --target i686-pc-windows-msvc'
          targets: 'i686-pc-windows-msvc'
          test: 'false'