on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:
  # For quickly detecting important differences in runner configurations
  schedule:
    - cron: '0 5 * * MON'

name: Windows i686

jobs:
  test:
    name: Test
    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: ./.github/actions/post-checkout
        with:
          playtime-engine-deploy-key: ${{ secrets.PRIVATE_PLAYTIME_CLIP_ENGINE_DEPLOY_KEY }}
          license-processor-deploy-key: ${{ secrets.PRIVATE_HELGOBOSS_LICENSE_PROCESSOR_DEPLOY_KEY }}
      - uses: ./.github/actions/test
        with:
          features: 'egui'
          targets: 'i686-pc-windows-msvc'
          # Prevent "LLVM ERROR: out of memory"
          args: '--profile dev-llvm-out-of-memory-fix --target i686-pc-windows-msvc'
      # Remainder
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: 1.84.0-i686-pc-windows-msvc
          target: i686-pc-windows-msvc
          override: true
      - name: cargo build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --features egui